version: '3.8'
services:
  game:
    build: .
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
    environment:
      - DISPLAY=$DISPLAY
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    devices:
      - "/dev/snd:/dev/snd"
    network_mode: "host"
    privileged: true

